### PR TITLE
Multiple commits relating to Bug #7 and Bug #313

### PR DESCRIPTION
**Pull request by alexharpin**
vyatta-openvpn: correct a typo in server mode reset message.

Correct a typo in vyatta-reset-client-ovpn.pl for the message returned
when resetting a client in server mode.

vyatta-openvpn: correct a typo in the persistent-tunnel template

Correct a typo in the persistent-tunnel template node.def introduced
for Bug #7 and Bug #313

vyatta-openvpn: correct wrong node name usage for persistent tunnels

Correction for wrong node name usage in the code for persistent openvpn
tunnels, added for Bug #7 and Bug #313

vyatta-openvpn: persistent tunnels in server mode and allow full reset

Allow OpenVPN tunnels (vtun) that are configured for server mode
operation to be set as persistent (TUN/TAP interfaces aren't closed
and reopened on a reset).  Check if the tunnel is configured for
persistence when 'reset openvpn interface' is run from the CLI, if it
then prompt the user if an interface reset is required along with the
tunnel reset (defaults to yes).

Bug #7 http://bugzilla.vyos.net/show_bug.cgi?id=7
Bug #313 http://bugzilla.vyos.net/show_bug.cgi?id=313

### CODE REVIEW

**Comment by alexharpin** [comment]
The typo in the template node.def and using the wrong node name are just embarrassing, working fine and tested on the VM and then managed to commit the wrong names.

**Comment by dmbaturin** [comment]
I was too busy trying to get the VXLAN package to build, so I missed it too.

**Comment by alexharpin** [comment]
Yeah, noticed all the changes going in for VXLAN while I was doing this, nice one.  I think it must have been looking at other bugs as well that did it, tunnels on one half of my brain and interfaces on the other, well that's my excuse anyway :)

**Comment by dmbaturin** [comment]
As long as it doesn't sneak into release, I'm ok with it. I once broke the Interface.pm by pushing a code with typo to git.vyatta.com, so I'm not without sin too. ;)

**Comment by alexharpin** [comment]
I normally copy the entire file(s) from my git copy to a VM to test, so avoiding the above, but I was in the process of replacing some of them for testing and must have bypassed that stage.  Confused me for a little bit when I was testing the last part (resetting persistent tunnels) and couldn't get them to persist, then realised what I'd done <facepalm>.

**Pull request merged**
