### PR TITLE
Allow Elliptic Curve Private Key

### PR DESCRIPTION
**Pull request by giga1699**

### CODE REVIEW

**Comment by giga1699** [comment]
OpenVPN 2.4 added support for ECC. Change allows for EC private keys to be used. Change works on 1.2.0-rolling+201902190337 after migrating an OpenVPN config from Ubuntu to VyOS using ECC certs/keys.

**Comment by c-po** [comment]
Rolling release runs: `OpenVPN 2.3.4-5+deb8u2` so this seems to be conflicting?

**Comment by jjakob** [comment]
@c-po rolling+201906231514 has ```2.4.0-6+deb9u1~bpo8+1```

**Comment by c-po** [comment]
This branch has conflicts that must be resolved.

Please also create a new Task at https:/phabricator.vyos.net as feature request and then prefix this commit with the Task for easy tracking.

https://vyos.readthedocs.io/en/latest/contributing/development.html#submit-a-patch

**Comment by giga1699** [comment]
Sorry about not creating the task! First time contributing.

I'll get that created and fix the conflicts.

**Comment by c-po** [comment]
Closing this as OpenVPN currently is rewritten from scratch.

**Pull request closed without merging**
